feat: use eslint

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,8 +27,19 @@ jobs:
       - name: Install
         run: pnpm install
 
-      - name: Lint
-        run: pnpm run lint
+      - name: ESLint check
+        run: pnpm lint
+
+      - name: Check if any errors
+        id: eslint-status
+        run: echo ::set-output name=has_errors::$(git diff --name-only origin/main | grep '\.jsx\?$' | xargs eslint --max-warnings=0 --format=compact || true)
+
+      - name: Fail if there are errors
+        run: |
+          if [ "${{ steps.eslint-status.outputs.has_errors }}" != "" ]; then
+            echo "ESLint check failed"
+            exit 1
+          fi
 
   typecheck:
     runs-on: ubuntu-latest
